[package]
name = "week5_async_stream_proc"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = {workspace = true}
